#!/usr/bin/env bash
#
# bootstrap.sh — one-shot server setup for the Drum Major Portal.
#
# After cloning the repo, run this once with sudo:
#
#   sudo ./deploy/bootstrap.sh [PUBLIC_URL]
#
# e.g.  sudo ./deploy/bootstrap.sh https://portal.myschool.org
#
# It is idempotent — re-running is safe. It will:
#   1. Install PostgreSQL (if missing) and start it.
#   2. Create the `portal` role + `drummajor_portal` database (if missing).
#   3. Generate /etc/drummajor-portal/portal.env with fresh secrets (if missing).
#   4. Make the update script executable.
#   5. Generate + install the systemd unit, then enable & start it.
#
# Node/npm must already be installed (Node 22 LTS). See deploy/README.md.
set -euo pipefail

# --- config ------------------------------------------------------------------
DB_NAME="drummajor_portal"
DB_USER="portal"
ENV_DIR="/etc/drummajor-portal"
ENV_FILE="$ENV_DIR/portal.env"
SERVICE_NAME="drummajor-portal"
PUBLIC_URL="${1:-http://localhost:3000}"

# Resolve the repo dir (parent of this script's deploy/ folder) and its owner.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(dirname "$SCRIPT_DIR")"
RUN_USER="$(stat -c '%U' "$APP_DIR")"
RUN_GROUP="$(stat -c '%G' "$APP_DIR")"

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: run with sudo (need root for apt, postgres, systemd)." >&2
  exit 1
fi

# Verify node/npm exist; capture their dir for the unit's PATH.
if ! command -v node >/dev/null 2>&1; then
  echo "ERROR: node not found. Install Node 22 LTS first (see deploy/README.md)." >&2
  exit 1
fi
NODE_BIN_DIR="$(dirname "$(command -v node)")"

echo "==> repo:    $APP_DIR (owner: $RUN_USER:$RUN_GROUP)"
echo "==> node:    $NODE_BIN_DIR"
echo "==> public:  $PUBLIC_URL"

# --- 1. PostgreSQL -----------------------------------------------------------
if ! command -v psql >/dev/null 2>&1; then
  echo "==> installing PostgreSQL ..."
  apt-get update -qq
  apt-get install -y -qq postgresql
fi
systemctl enable --now postgresql

# --- 2. role + database (idempotent) -----------------------------------------
# Reuse the DB password already in the env file if present, else generate one.
if [ -f "$ENV_FILE" ] && grep -q '^DATABASE_URL=' "$ENV_FILE"; then
  DB_PASS="$(sed -n 's/.*\/\/[^:]*:\([^@]*\)@.*/\1/p' "$ENV_FILE")"
  echo "==> reusing existing DB password from $ENV_FILE"
else
  DB_PASS="$(openssl rand -base64 24 | tr -d '/+=')"
  echo "==> generated new DB password"
fi

echo "==> ensuring role '$DB_USER' and database '$DB_NAME' ..."
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$DB_USER') THEN
    CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASS';
  ELSE
    ALTER ROLE $DB_USER PASSWORD '$DB_PASS';
  END IF;
END
\$\$;
SQL
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'" \
  | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USER"

DATABASE_URL="postgresql://$DB_USER:$DB_PASS@localhost:5432/$DB_NAME?schema=public"

# --- 3. env / secrets file ---------------------------------------------------
mkdir -p "$ENV_DIR"
if [ -f "$ENV_FILE" ]; then
  echo "==> $ENV_FILE exists; leaving it untouched."
else
  echo "==> writing $ENV_FILE with fresh secrets ..."
  APP_ENCRYPTION_KEY="$(openssl rand -base64 48)"
  AUTH_SECRET="$(openssl rand -base64 32)"
  cat > "$ENV_FILE" <<ENV
# Generated by deploy/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
DATABASE_URL="$DATABASE_URL"
APP_ENCRYPTION_KEY="$APP_ENCRYPTION_KEY"
AUTH_SECRET="$AUTH_SECRET"
NEXT_PUBLIC_BASE_URL="$PUBLIC_URL"
AUTH_URL="$PUBLIC_URL"
NODE_ENV="production"
ENV
fi
chown root:"$RUN_GROUP" "$ENV_FILE"
chmod 640 "$ENV_FILE"

# --- 4. update script --------------------------------------------------------
chmod +x "$SCRIPT_DIR/update-and-run.sh"

# --- 5. systemd unit (generated so paths/user are always correct) ------------
echo "==> installing systemd unit /etc/systemd/system/$SERVICE_NAME.service ..."
cat > "/etc/systemd/system/$SERVICE_NAME.service" <<UNIT
# Generated by deploy/bootstrap.sh. Edit bootstrap.sh and re-run to change.
[Unit]
Description=Drum Major Portal (Next.js)
After=network.target postgresql.service
Wants=postgresql.service

[Service]
Type=simple
User=$RUN_USER
Group=$RUN_GROUP
WorkingDirectory=$APP_DIR
EnvironmentFile=$ENV_FILE
Environment=PATH=$NODE_BIN_DIR:/usr/local/bin:/usr/bin:/bin
ExecStart=$SCRIPT_DIR/update-and-run.sh
TimeoutStartSec=0
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=false

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME"

echo
echo "==> done. Service '$SERVICE_NAME' is up. Watch it with:"
echo "    journalctl -u $SERVICE_NAME -f"
